[build-system]
requires = ["flit_core >=3.2,<4"]
build-backend = "flit_core.buildapi"

[project]
name = "Stacked CMS"
authors = [{name = "Lawrence", email = "lawrence@stackedcms.com"}]
dynamic = ["version", "description"]
